#!/usr/bin/env python3
"""
Optimize the team coordination margin for XAE-12-Team.py.

Put this file next to automated_RobotTest.py.
Put current_team_params.py inside the Robots/ folder.
XAE-12-Team.py must read TEAM_GOLD_MARGIN from current_team_params.py.

Example:
python optimization_runner_team_margin.py --maps Game/Maps/maze_map.dat --rounds 1000 --games 20
"""

import argparse
import csv
import re
import subprocess
import sys
import time
from pathlib import Path

MARGINS = [0, 2, 3, 5, 7, 10]

RESULT_RE = re.compile(
    r"^(?P<team>.+?):\s+"
    r"(?P<wins>\d+) wins \((?P<winrate>[\d.]+)%\) \| "
    r"Avg Gold: (?P<avg_gold>[\d.]+) \| "
    r"Avg Distance: (?P<avg_distance>[\d.]+) \| "
    r"Avg Moves: (?P<avg_moves>[\d.]+) \| "
    r"Avg Health: (?P<avg_health>[\d.]+)"
)


def write_param_file(path: Path, margin: int):
    path.write_text(
        "# Auto-generated by optimization_runner_team_margin.py\n"
        f"TEAM_GOLD_MARGIN = {margin!r}\n",
        encoding="utf-8",
    )


def parse_stats(output: str):
    stats = {}
    for line in output.splitlines():
        match = RESULT_RE.match(line.strip())
        if not match:
            continue
        d = match.groupdict()
        team = d.pop("team")
        stats[team] = {
            "wins": int(d["wins"]),
            "winrate": float(d["winrate"]),
            "avg_gold": float(d["avg_gold"]),
            "avg_distance": float(d["avg_distance"]),
            "avg_moves": float(d["avg_moves"]),
            "avg_health": float(d["avg_health"]),
        }
    return stats


def run_test(script: Path, map_file: str, rounds: int, games: int, python_exe: str):
    cmd = [
        python_exe,
        str(script),
        "--map", map_file,
        "--number", str(rounds),
        "--games", str(games),
    ]
    completed = subprocess.run(cmd, capture_output=True, text=True)
    return completed.returncode, completed.stdout, completed.stderr


def main():
    parser = argparse.ArgumentParser(description="Optimize XAE-12 team margin.")
    parser.add_argument("--tester", default="automated_RobotTest.py")
    parser.add_argument("--target", default="XAE12Team")
    parser.add_argument("--maps", nargs="+", required=True)
    parser.add_argument("--rounds", type=int, default=1000)
    parser.add_argument("--games", type=int, default=20)
    parser.add_argument("--margins", nargs="+", type=int, default=MARGINS)
    args = parser.parse_args()

    root = Path(__file__).resolve().parent
    tester = root / args.tester
    robots_dir = root / "Robots"
    param_file = robots_dir / "current_team_params.py"
    raw_dir = root / "raw_team_margin_outputs"
    raw_dir.mkdir(exist_ok=True)

    if not tester.exists():
        raise FileNotFoundError(f"Tester not found: {tester}")
    if not robots_dir.exists():
        raise FileNotFoundError(f"Robots folder not found: {robots_dir}")

    result_csv = root / "team_margin_results.csv"
    summary_csv = root / "team_margin_summary.csv"

    result_fields = [
        "margin", "map", "wins", "winrate", "avg_gold", "avg_distance",
        "avg_moves", "avg_health", "raw_output_file", "returncode",
    ]

    all_rows = []
    started = time.time()

    with result_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=result_fields)
        writer.writeheader()

        for i, margin in enumerate(args.margins, start=1):
            write_param_file(param_file, margin)
            print(f"\n[{i}/{len(args.margins)}] Testing TEAM_GOLD_MARGIN={margin}", flush=True)

            for map_file in args.maps:
                print(f"  map={map_file}", flush=True)
                returncode, stdout, stderr = run_test(
                    script=tester,
                    map_file=map_file,
                    rounds=args.rounds,
                    games=args.games,
                    python_exe=sys.executable,
                )

                raw_name = f"margin_{margin}_{Path(map_file).stem}.txt"
                raw_path = raw_dir / raw_name
                raw_path.write_text(stdout + "\n\n--- STDERR ---\n" + stderr, encoding="utf-8")

                stats = parse_stats(stdout)
                target_stats = stats.get(args.target)

                if target_stats is None:
                    print(f"    WARNING: target {args.target!r} not found in output. Check robot_module_names.")
                    target_stats = {
                        "wins": 0,
                        "winrate": 0.0,
                        "avg_gold": 0.0,
                        "avg_distance": 0.0,
                        "avg_moves": 0.0,
                        "avg_health": 0.0,
                    }

                row = {
                    "margin": margin,
                    "map": map_file,
                    **target_stats,
                    "raw_output_file": str(raw_path),
                    "returncode": returncode,
                }
                writer.writerow(row)
                f.flush()
                all_rows.append(row)

    grouped = {}
    for row in all_rows:
        grouped.setdefault(row["margin"], []).append(row)

    summaries = []
    for margin, rows in grouped.items():
        n = len(rows)
        summaries.append({
            "margin": margin,
            "mean_winrate": sum(r["winrate"] for r in rows) / n,
            "mean_avg_gold": sum(r["avg_gold"] for r in rows) / n,
            "mean_avg_health": sum(r["avg_health"] for r in rows) / n,
            "mean_avg_moves": sum(r["avg_moves"] for r in rows) / n,
            "maps_tested": n,
        })

    summaries.sort(key=lambda r: (r["mean_winrate"], r["mean_avg_gold"], r["mean_avg_health"]), reverse=True)

    summary_fields = ["margin", "mean_winrate", "mean_avg_gold", "mean_avg_health", "mean_avg_moves", "maps_tested"]
    with summary_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=summary_fields)
        writer.writeheader()
        writer.writerows(summaries)

    elapsed_min = (time.time() - started) / 60
    print("\nDone.")
    print(f"Wrote {result_csv}")
    print(f"Wrote {summary_csv}")
    print(f"Elapsed: {elapsed_min:.1f} minutes")
    print("\nTop margins:")
    for row in summaries:
        print(
            f"margin={row['margin']} winrate={row['mean_winrate']:.1f}% "
            f"gold={row['mean_avg_gold']:.1f} health={row['mean_avg_health']:.1f} "
            f"moves={row['mean_avg_moves']:.1f}"
        )


if __name__ == "__main__":
    main()
