#!/usr/bin/env python3
"""
Parameter optimizer for XAE-12-S3_1.

Put this file next to automated_RobotTest.py.
Put XAE-12-S3_1.py and current_s31_params.py inside the Robots/ folder.
Run for example:

python optimization_runner.py --maps Game/Maps/maze_map.dat Game/Maps/cross_map.dat --rounds 1000 --games 20

The script writes:
- optimization_results.csv      all tested map/config results
- optimization_summary.csv      one averaged score per config
- raw_optimization_outputs/     full terminal output for debugging
"""

import argparse
import csv
import itertools
import random
import re
import subprocess
import sys
import time
from pathlib import Path

# Start with a deliberately small grid. Expand only after the whole pipeline works.
PARAM_GRID = {
    # Sprint / gold economy
    "MAX_BURST_MOVES": [5],
    "GOLD_SPEND_FRACTION": [0.25, 0.30],
    "MINIMUM_GOLD_RESERVE": [20, 30],

    # Path acceptance / exploration
    "GOLD_PATH_FACTOR": [1.5, 2.0, 2.5],
    "GOLD_PATH_BONUS": [3, 5],
    "FRONTIER_GOLD_WEIGHT": [0.5, 0.8],

    # High-budget behavior
    "HIGH_BUDGET_THRESHOLD": [80, 100],
    "HIGH_BUDGET_BURST": [3],
}

# These stay fixed during the first optimization stage.
FIXED_PARAMS = {
    "DEFAULT_ENEMY_SPEED": 2.0,
    "MIN_PROFIT_NORMAL": 1,
    "MIN_PROFIT_RIVALRY": 0,
    "RIVALRY_SCORE_MARGIN": 25,
    "LOST_POT_ENEMY_DISTANCE": 2,
}

RESULT_RE = re.compile(
    r"^(?P<team>.+?):\s+"
    r"(?P<wins>\d+) wins \((?P<winrate>[\d.]+)%\) \| "
    r"Avg Gold: (?P<avg_gold>[\d.]+) \| "
    r"Avg Distance: (?P<avg_distance>[\d.]+) \| "
    r"Avg Moves: (?P<avg_moves>[\d.]+) \| "
    r"Avg Health: (?P<avg_health>[\d.]+)"
)


def iter_configs():
    keys = list(PARAM_GRID)
    for values in itertools.product(*(PARAM_GRID[key] for key in keys)):
        config = dict(zip(keys, values))
        config.update(FIXED_PARAMS)
        yield config


def write_param_file(path: Path, config: dict):
    lines = ["# Auto-generated by optimization_runner.py\n"]
    for key in sorted(config):
        lines.append(f"{key} = {config[key]!r}\n")
    path.write_text("".join(lines), encoding="utf-8")


def parse_stats(output: str):
    stats = {}
    for line in output.splitlines():
        match = RESULT_RE.match(line.strip())
        if not match:
            continue
        d = match.groupdict()
        team = d.pop("team")
        stats[team] = {
            "wins": int(d["wins"]),
            "winrate": float(d["winrate"]),
            "avg_gold": float(d["avg_gold"]),
            "avg_distance": float(d["avg_distance"]),
            "avg_moves": float(d["avg_moves"]),
            "avg_health": float(d["avg_health"]),
        }
    return stats


def run_test(script: Path, map_file: str, rounds: int, games: int, python_exe: str):
    cmd = [
        python_exe,
        str(script),
        "--map", map_file,
        "--number", str(rounds),
        "--games", str(games),
    ]
    completed = subprocess.run(cmd, capture_output=True, text=True)
    return completed.returncode, completed.stdout, completed.stderr


def main():
    parser = argparse.ArgumentParser(description="Optimize XAE-12-S3_1 parameters.")
    parser.add_argument("--tester", default="automated_RobotTest.py", help="test script to call")
    parser.add_argument("--target", default="StrategyThreeOneBot", help="team name printed by automated_RobotTest.py")
    parser.add_argument("--maps", nargs="+", required=True, help="map files to test")
    parser.add_argument("--rounds", type=int, default=1000, help="rounds per game")
    parser.add_argument("--games", type=int, default=20, help="games per config per map")
    parser.add_argument("--max-configs", type=int, default=None, help="optional cap for quick tests")
    parser.add_argument("--random-sample", action="store_true", help="sample configs randomly instead of taking first N")
    parser.add_argument("--seed", type=int, default=1)
    args = parser.parse_args()

    root = Path(__file__).resolve().parent
    tester = root / args.tester
    robots_dir = root / "Robots"
    param_file = robots_dir / "current_s31_params.py"
    raw_dir = root / "raw_optimization_outputs"
    raw_dir.mkdir(exist_ok=True)

    if not tester.exists():
        raise FileNotFoundError(f"Tester not found: {tester}")
    if not robots_dir.exists():
        raise FileNotFoundError(f"Robots folder not found: {robots_dir}")

    configs = list(iter_configs())
    random.seed(args.seed)
    if args.random_sample:
        random.shuffle(configs)
    if args.max_configs is not None:
        configs = configs[:args.max_configs]

    result_csv = root / "optimization_results.csv"
    summary_csv = root / "optimization_summary.csv"

    parameter_names = sorted(configs[0]) if configs else []
    result_fields = [
        "config_id", "map", *parameter_names,
        "wins", "winrate", "avg_gold", "avg_distance", "avg_moves", "avg_health",
        "raw_output_file", "returncode",
    ]

    all_rows = []
    started = time.time()

    with result_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=result_fields)
        writer.writeheader()

        for config_id, config in enumerate(configs, start=1):
            write_param_file(param_file, config)
            print(f"\n[{config_id}/{len(configs)}] Testing {config}", flush=True)

            for map_file in args.maps:
                print(f"  map={map_file}", flush=True)
                returncode, stdout, stderr = run_test(
                    script=tester,
                    map_file=map_file,
                    rounds=args.rounds,
                    games=args.games,
                    python_exe=sys.executable,
                )

                raw_name = f"config_{config_id:04d}_{Path(map_file).stem}.txt"
                raw_path = raw_dir / raw_name
                raw_path.write_text(stdout + "\n\n--- STDERR ---\n" + stderr, encoding="utf-8")

                stats = parse_stats(stdout)
                target_stats = stats.get(args.target)

                if target_stats is None:
                    print(f"    WARNING: target {args.target!r} not found in output. Check robot_module_names.")
                    target_stats = {
                        "wins": 0,
                        "winrate": 0.0,
                        "avg_gold": 0.0,
                        "avg_distance": 0.0,
                        "avg_moves": 0.0,
                        "avg_health": 0.0,
                    }

                row = {
                    "config_id": config_id,
                    "map": map_file,
                    **{key: config[key] for key in parameter_names},
                    **target_stats,
                    "raw_output_file": str(raw_path),
                    "returncode": returncode,
                }
                writer.writerow(row)
                f.flush()
                all_rows.append(row)

    # Average each config across maps.
    grouped = {}
    for row in all_rows:
        grouped.setdefault(row["config_id"], []).append(row)

    summary_fields = [
        "config_id", *parameter_names,
        "mean_winrate", "mean_avg_gold", "mean_avg_health", "mean_avg_moves", "maps_tested",
    ]

    summaries = []
    for config_id, rows in grouped.items():
        first = rows[0]
        n = len(rows)
        summaries.append({
            "config_id": config_id,
            **{key: first[key] for key in parameter_names},
            "mean_winrate": sum(r["winrate"] for r in rows) / n,
            "mean_avg_gold": sum(r["avg_gold"] for r in rows) / n,
            "mean_avg_health": sum(r["avg_health"] for r in rows) / n,
            "mean_avg_moves": sum(r["avg_moves"] for r in rows) / n,
            "maps_tested": n,
        })

    summaries.sort(key=lambda r: (r["mean_winrate"], r["mean_avg_gold"], r["mean_avg_health"]), reverse=True)

    with summary_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=summary_fields)
        writer.writeheader()
        writer.writerows(summaries)

    elapsed_min = (time.time() - started) / 60
    print("\nDone.")
    print(f"Wrote {result_csv}")
    print(f"Wrote {summary_csv}")
    print(f"Elapsed: {elapsed_min:.1f} minutes")
    print("\nTop 10 configs:")
    for row in summaries[:10]:
        print(
            f"#{row['config_id']} winrate={row['mean_winrate']:.1f}% "
            f"gold={row['mean_avg_gold']:.1f} health={row['mean_avg_health']:.1f} "
            f"moves={row['mean_avg_moves']:.1f}"
        )


if __name__ == "__main__":
    main()
